name: advent-of-code
version: 0.2.0.0
github: "godu/advent-of-code-2020"
license: BSD3
author: Arthur Weber
maintainer: arthur.weber@viacesi.fr

extra-source-files:
  - README.md

description: |
  Please see the README on GitHub
  at <https://github.com/godu/advent-of-code-2020#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - arithmoi
    - containers
    - extra
    - split
    - vector

executables:
  advent-of-code-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - advent-of-code
    ghc-options:
      - -O2
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  advent-of-code-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - advent-of-code
      - hspec
      - containers
      - vector
